package handler

// Localize errors generated by this gateway. Arbitrary upstream error bodies
// and administrator-defined passthrough messages are not translated or guessed.
func openAIClientError(errType, code, message string) (string, string, string) {
	translations := map[string][2]string{
		"Upstream request timed out, please retry later": {"UPSTREAM_TIMEOUT", "上游响应超时，请稍后在当前会话重试"},
		"Invalid API key":                                                        {"LOCAL_API_KEY_INVALID", "本地认证失败：API Key 无效"},
		"User context not found":                                                 {"LOCAL_USER_CONTEXT_MISSING", "本地认证状态异常，请重新验证 API Key"},
		"Failed to read request body":                                            {"LOCAL_REQUEST_READ_FAILED", "本地请求校验未通过：读取请求内容失败"},
		"Failed to parse request body":                                           {"LOCAL_REQUEST_JSON_INVALID", "本地请求校验未通过：JSON 格式无效"},
		"Request body is empty":                                                  {"LOCAL_REQUEST_BODY_EMPTY", "本地请求校验未通过：请求内容为空"},
		"model is required":                                                      {"LOCAL_REQUEST_MODEL_MISSING", "本地请求校验未通过：缺少 model 参数"},
		"No available accounts":                                                  {"LOCAL_NO_AVAILABLE_ACCOUNTS", "本地调度失败：没有满足权限、模型和可用状态要求的渠道，请稍后重试"},
		"Service temporarily unavailable":                                        {"LOCAL_SERVICE_UNAVAILABLE", "本地服务暂时不可用，请稍后重试"},
		"Service temporarily unavailable, please retry later":                    {"LOCAL_SERVICE_UNAVAILABLE", "本地服务暂时不可用，请稍后重试"},
		"Too many pending requests, please retry later":                          {gatewayQueueFullCode, "本地请求队列已满，请稍后重试"},
		"Concurrency limit exceeded for account, please retry later":             {gatewayConcurrencyLimitCode, "本地渠道并发已满，请稍后重试"},
		"Concurrency limit exceeded for user, please retry later":                {gatewayConcurrencyLimitCode, "本地用户并发已满，请稍后重试"},
		"All available accounts are currently rate-limited. Please retry later.": {"LOCAL_ALL_ACCOUNTS_COOLDOWN", "本地调度失败：可用渠道均在限流冷却中，请稍后重试"},
		"No available accounts support /responses/compact":                       {"LOCAL_COMPACT_UNSUPPORTED", "本地调度失败：没有可用渠道支持历史压缩接口"},
		"Upstream authentication failed, please contact administrator":           {"UPSTREAM_AUTHENTICATION_FAILED", "上游认证失败，请联系管理员检查渠道凭据"},
		"Upstream access forbidden, please contact administrator":                {"UPSTREAM_ACCESS_FORBIDDEN", "上游拒绝访问，请联系管理员检查渠道权限"},
		"Upstream rate limit exceeded, please retry later":                       {"UPSTREAM_RATE_LIMITED", "上游请求受限或额度已用完，请稍后重试"},
		"Upstream service overloaded, please retry later":                        {"UPSTREAM_OVERLOADED", "上游服务繁忙，请稍后重试"},
		"Upstream service temporarily unavailable":                               {"UPSTREAM_UNAVAILABLE", "上游服务暂时不可用，请稍后在当前会话重试"},
		"Upstream request failed":                                                {"UPSTREAM_REQUEST_FAILED", "上游请求失败，请稍后在当前会话重试"},
	}
	if value, ok := translations[message]; ok {
		if code == "" {
			code = value[0]
		}
		message = value[1]
	}
	return errType, code, message
}
